### ISSUE TITLE
JWT secured on upload keys

### ISSUE THREAD

**Issue by srmontero06** [notifyme-app/notifyme-sdk-backend#8]
Upload tracekeys endpoint is secured with a jwt.
https://github.com/notifyme-app/notifyme-sdk-backend/blob/d1a862b523334a7e93be5a4482128ff8ea4e6c07/notifyme-sdk-backend/notifyme-sdk-backend-ws/src/main/java/ch/ubique/notifyme/sdk/backend/ws/config/JwtConfig.java#L63

Where this jwt comes from?
Documentation does not specify anything about this token but it's quite similar to DP3T project, where you have to validate a code returning a jwt token valid.

**Comment by martinalig** [comment]
Hi
The secured enpoint for uploading is still work in progress. The idea is to have a similar setup as in dp3t, where the uploader must obtain a JWT token first from an (health)-authority, and then can use this JWT token to upload the keys.

The debug endpoint is currently used by notifyme, as the health-authoritty has not yet been integrated into the system.

We plan to complete the JWT development in the next few weeks.

**Comment by srmontero06** [comment]
Thanks. We'll be careful to this development.
